### ISSUE TITLE
unresolved dependency: bwblib

### ISSUE THREAD

**Issue by memmett** [bwbecker/electionSim#1]
Hello, I stumbled upon this repository and was fascinated! I tried running it, but I get:

`[error] (*:update) sbt.ResolveException: unresolved dependency: ca.bwbecker#bwblib_2.11;1.2: not found`

when trying to compile it. I don't see any references to bwblib online. I'm new to Scala, so apologies if I am missing something obvious.

Any suggestions? Thanks!

**Comment by bwbecker** [comment]
Sorry.  That's a personal library of Scala utility functions.  Published now at https://github.com/bwbecker/bwbLib
